### ISSUE TITLE
Upload table not possible after table was deleted

### ISSUE THREAD

**Issue by mtstahl** [pekrau/DbShare#327]
I uploaded a table from a `csv` file. Then I deleted the whole table again. The database was now empty. Then I clicked on <Upload table> to add another table from `csv`.

However, I got the following message:
`Error: size quota exceeded; cannot add data`.

Workaround: I had to delete the whole database and recreated it.

**Comment by pekrau** [comment]
Thanks,

I think I know what the problem is.

Sqlite3 does not shrink its file automatically after table delete.
Currently one has to do that manually by clicking "Vacuum" for the database.

This is arguably a bug. Will make vacuum automatic after table delete.

By the way, do you need a larger quota? The default is pretty low.

Yours,
Per K

Den fre 24 maj 2019 10:05Matthias Stahl <notifications@github.com> skrev:

**Comment by mtstahl** [comment]
So far it works for the tests I'm running, thanks!
